In [90]:
import pandas as pd

In [91]:
df = pd.read_csv("./FoodList.csv", encoding = 'utf-8')

In [89]:
df.replace('-','0',inplace=True)
d_f = pd.DataFrame(df)
d_f.to_csv("./FoodList.csv",encoding='utf-8')

,No.,SAMPLE_ID,식품명,1회제공량(g),에너지(Kcal),단백질(g),지방(g),탄수화물(g),총당류(g),나트륨(mg)
0,1,D018620-ZZ-AVG,채소 초밥,280,393.260,7.590,1.370,87.640,0,144.480
1,2,D018186-ZZ-AVG,검정콩밥,200,330.610,9.060,2.230,68.590,0,6.870
2,3,D018187-ZZ-AVG,계란볶음밥,260,584.710,17.220,29.320,62.990,0.44,827.600
3,4,D018188-ZZ-AVG,고추김밥,290,490.730,14.140,12.780,79.800,0.27,948.040
4,5,D018189-ZZ-AVG,기장밥,200,331.910,6.870,1.140,73.530,0,2.790
...,...,...,...,...,...,...,...,...,...,...
83,84,D000253-ZZ-AVG,충무김밥,400,583.926,23.425,5.956,109.156,17.189,1294.268
84,85,D000258-ZZ-AVG,한치초밥,250,374.180,13.712,0.848,77.923,13.13,1199.310
85,86,D000259-ZZ-AVG,해물덮밥,700,771.933,42.037,22.443,100.449,1.194,1802.681
86,87,D000260-ZZ-AVG,해물볶음밥,400,705.217,25.105,26.996,90.459,1.222,1074.349
87,88,D000261-ZZ-AVG,회덮밥,500,683.018,30.210,16.553,103.300,10.925,744.270

In [81]:
eat = input('밥을 입력하세요 : ')
eat

밥을 입력하세요 : 채소 초밥

'채소 초밥'

In [82]:
find_row = df.loc[df['식품명'] == eat ]
find_row

,No.,SAMPLE_ID,식품명,1회제공량(g),에너지(Kcal),단백질(g),지방(g),탄수화물(g),총당류(g),나트륨(mg)
0,1,D018620-ZZ-AVG,채소 초밥,280,393.26,7.59,1.37,87.64,0,144.48

In [83]:
kcal = find_row.loc[:,'에너지(Kcal)']
int(kcal)

393